"use client";
import { ArrowLeft, FileText } from "lucide-react";
import { useRouter } from "next/navigation";

export default function TermsOfService() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-[#020617] text-slate-300 p-6 md:p-12 font-sans relative overflow-hidden">
      <div className="fixed top-[-20%] right-[-10%] w-[50%] h-[50%] bg-purple-600/10 blur-[150px] rounded-full pointer-events-none"></div>
      
      <div className="max-w-4xl mx-auto relative z-10">
        <button onClick={() => router.push('/')} className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors font-semibold mb-8">
          <ArrowLeft size={18} /> Back to Home
        </button>

        <div className="bg-slate-900/60 backdrop-blur-xl border border-slate-700/50 p-8 md:p-12 rounded-[2.5rem] shadow-2xl">
          <div className="flex items-center gap-4 mb-8 border-b border-slate-800 pb-8">
            <div className="w-16 h-16 bg-purple-500/20 rounded-2xl flex items-center justify-center">
              <FileText size={32} className="text-purple-400"/>
            </div>
            <div>
              <h1 className="text-3xl md:text-4xl font-extrabold text-white">Terms of Service</h1>
              <p className="text-slate-400 mt-2">Effective Date: February 2026</p>
            </div>
          </div>

          <div className="space-y-8 text-sm md:text-base leading-relaxed">
            <section>
              <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing and using Talexo, you agree to be bound by these Terms of Service. If you do not agree, please do not use our platform.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">2. User Accounts & Integrity</h2>
              <p>You must provide accurate and complete information when creating an account. Falsifying educational qualifications (like CA/CMA attempts or clearing status) or employment history will result in permanent ban from the platform.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">3. Exam and Assessment Rules</h2>
              <ul className="list-disc pl-5 space-y-2 mt-2">
                <li>Assessments must be taken individually without external help.</li>
                <li>Copying, pasting, or switching tabs during an exam is strictly prohibited.</li>
                <li>Receiving 3 warnings during a test will lead to immediate termination and a "Disqualified" status on your profile.</li>
                <li>Scores generated by our AI Assessment Engine are final and cannot be challenged manually.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">4. For Companies & Recruiters</h2>
              <p>Companies using Talexo to hire candidates must maintain professional conduct. Data accessed from candidate profiles must be used strictly for hiring purposes and not sold to third-party marketing agencies.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">5. Termination</h2>
              <p>Talexo administrators reserve the right to suspend or terminate your account at any time for violations of these Terms, suspected fraud, or cheating during skill assessments.</p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}